# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def common_pods!
  pod "Delayed",">2"
end


target 'Flask-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  common_pods!

  target 'Flask-iOSTests' do
    inherit! :search_paths
    common_pods!
  end

end

target 'Flask-macOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  common_pods!

  target 'Flask-macOSTests' do
    inherit! :search_paths
    common_pods!
  end

end

target 'Flask-tvOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  common_pods!

  target 'Flask-tvOSTests' do
    inherit! :search_paths
    common_pods!
  end

end
