# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def common_pods!
    pod 'Delayed','~>2.2.2'
end

target 'Reaktor-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
common_pods!
  # Pods for Reaktor-iOS
  pod 'Delayed','~>2.2.2'
  target 'Reaktor-iOSTests' do
    inherit! :search_paths
    common_pods!
    # Pods for testing
  end

end

target 'Reaktor-macOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Reaktor-macOS
common_pods!
  target 'Reaktor-macOSTests' do
    inherit! :search_paths
    # Pods for testing
    common_pods!
  end

end

target 'Reaktor-tvOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Reaktor-tvOS
common_pods!
  target 'Reaktor-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    common_pods!
  end

end
